apiVersion: v1
kind: Pod
metadata:
  namespace: guestbook   
  name: redis-pod
  labels:
    name: redis-pod
    app: web-app
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
     - containerPort: 6379