apiVersion: v1
kind: Service
metadata:
  namespace: guestbook  
  name: redis
  labels:
    name: redis-service
    app: web-app
spec:
  ports:
  - port: 6379
    name: redis-service
    targetPort: 6379
  selector:
     name: redis-pod
     app: web-app